name: Label request
on: pull_request

jobs:
  request-label:

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Script
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          previews: symmetra
          script: |
            const labels = await github.issues.listLabelsOnIssue({ ...context.issue })
            console.log(`labels: ${labels}`)
            const partnerLabelExists = labels.reduce((exists, label) => (
              exists ? true : label.startsWith('partner:')
            ), false)
            console.log(`context: ${JSON.stringify(context, null, 2)}`)
            console.log(`partnerLabelExists ${partnerLabelExists}`)
            if (!partnerLabelExists) {
              await github.issues.createComment({
                ...context.issue,
                body: 'Thanks for the contribution! To help us track and review this PR, **please assign a `partner:` label**. Thanks!'
              })
            }
