name: Check labels
on:
  pull_request:
    types: [opened]

jobs:
  partner-label:

    runs-on: ubuntu-latest

    steps:
      - name: GitHub Script
        uses: actions/github-script@0.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const partnerLabelExists = context.payload.pull_request.labels.reduce(
              (exists, label) => (exists ? true : label.name.startsWith('partner:')),
              false,
            )
            console.log(`partnerLabelExists ${partnerLabelExists}`)
            if (!partnerLabelExists) {
              await github.issues.createComment({
                ...context.issue,
                body:
                  `Thanks for the contribution, @${context.payload.pull_request.user.login}!\n\n` +
                  'To help us track and review this PR, **please assign a `partner:` label**, thanks!',
              })
            }
